compiler_version:          # [linux]
    - 11.2.0               # [linux]
cxx_compiler_version:      # [linux]
    - 11.2.0               # [linux]
cdt_name: cos7             # [linux]
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - '10.14'                # [osx]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - '10.14'                # [osx and x86_64]

